### ISSUE TITLE
How can I get full list of all available categories ?

### ISSUE THREAD

**Issue by PetroGromovo** [QuizApi/QuizAPI-BASH#13]
Working with quizapi library and reading at docs https://quizapi.io/docs/1.0/overview  how to set category 
I did not find where can I get full list of all available categories ?

When I tried to set to category value "Kubernetes"(this category is mentioned in quizapi overview) I got 404 error, No questions found...

Thanks in advance!

**Comment by bobbyiliev** [comment]
Hey @PetroGromovo!

You should pass the tag instead, most questions are organized by tags.

 I've gone ahead and added 2 new endpoints:

Helper endpoints:

* **Tags endpoint**: `/api/v1/tags` - returns all available tags. This is how most questions are organized.
* **Categories endpoint**:  `/api/v1/categories` - returns all available categories.

Hope that this helps!
