### ISSUE TITLE
Bug: typo in docs

### ISSUE THREAD

**Issue by FalseDev** [QuizApi/QuizAPI-BASH#6]
### Describe the bug
A typo in the authentication docs [here](https://quizapi.io/docs/1.0/authentication)

> You can attach your API key to a request in one of three ways:
> 1. apiKey querystring parameter.
> 2. X-Api-Key HTTP header.

There are only two authentication strategies listed while the line above states there are three

I know this is tiny but it's still worth fixing.

Thank you!

**Comment by bobbyiliev** [comment]
Hi there 👋,

Thank you for reporting this! 

This has now been fixed.

Regards,
Bobby
