### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by SouvikGhosh05** [QuizApi/QuizAPI-BASH#8]
Hello there, I did exactly what is written in the documentation. I previously opened an issue but you closed that issue, I got no meaningful response from you end. I got the API keys, I'm getting API responses absolutely fine but that's not my issue.
### Describe the bug

There are many parameter I can pass in the code like _limit_ and _category_  are the most important parameters to fetch what category of questions I want to get etc... But, I'm getting questions from other category too, like _kubernetes, docker_ or _devops_ etc, even though I want questions particularly from **linux** or as I have put in the querystring.
Here it is my code in Python:--- 

```
import requests
import json

url = "https://quizapi.io/api/v1/questions"

querystring = {
    "category" :  "Linux",
    "limit"    :  '5'
}

headers = {
    "X-Api-Key": "eRsMi........................" (my API Key)
}

response= requests.get(url=url, headers=headers, data=querystring).json()
for x in response:
    print(x['category'])

with open('linux_questions.json', 'w') as outfile:
    json.dump(response, outfile, indent=4)
```
Here, in the above code I wanted question exactly from **linux**, that what I wanted, but if you run this code with your API key you will see in the json file that there are lots of questions from the category also, which is unintended. Limit parameter is also not working, I'm getting 12 questions but I set limit only **5**.
Here are screenshots below, 

![Screenshot (339)](https://user-images.githubusercontent.com/42302494/126077540-7819dd30-2ea2-46e9-b0b8-7deeac84f911.png)
![Screenshot (341)](https://user-images.githubusercontent.com/42302494/126077552-ec639ff9-3674-4059-928c-3f5f47428564.png)
As you've seen there lots of question from other categories it was kinda overwhelming to see.

The good point is the quality of questions it sends, is very good and those are very knowledgable also, that's why I'm willing to use your service, I'm looking forward to see its solution. 🤞
Thank you! ☺️

**Comment by bobbyiliev** [comment]
This is quite interesting, just tested this with curl and PHP and it works with both.

But for some reason when using your script, the parameters are being stripped out. 

As this is a GET request,  `data = data` should be changed to `params = data` but it still does not work. 

Just checked the logs and it seems like the request parameters are in place:

```
"GET /api/v1/questions?apiKey=MY_KEY&category=Linux&limit=1 HTTP/2.0" 401 27 "-" "python-requests/2.25.1"
```

But still 401 is returned, though with curl it works well:

```
"GET /api/v1/questions?apiKey=MY_KEY&category=Linux&limit=1 HTTP/1.1" 200 793 "-" "curl/7.74.0"
```

Only difference is the user agent, maybe something on the QuizAPI server is blocking the `"python-requests/2.25.1"` agent.

**Comment by bobbyiliev** [comment]
A quick 'fix' is to specify the user agent in your header:

```
headers = {
    "X-Api-Key": "123qwe123",
    'User-Agent': 'curl/7.74.0',
}
```

Not ideal but should work as expected. Will look into this further for a permanent fix.

**Comment by SouvikGhosh05** [comment]
Thanks! @bobbyiliev, it's now working with the given user agent as you mentioned. Include this issue in its documentation for others to code in Python in order to remove their confusion. Thanks for your time. 😎
