### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by SouvikGhosh05** [QuizApi/QuizAPI-BASH#9]
### Can't fetch questions from other categories except Linux

As the previous issue I posted, I was trying to fetch linux questions. I successfully got the questions for this category.

Now, I'm trying to fetch questions from other categories as well. I can't fetch questions for _Kubernetes_ , _Cloud_, _Programming_, _Networking_. It just saying `{
    "error": "No questions found"
}` . I'm only getting question for _Linux_, _DevOps_, _Docker_.

### My example code
Suppose I'm trying to fetch all programming questions and dumping into a json file.
```
import requests
import json

url = "https://quizapi.io/api/v1/questions"

querystring = {
    "category" :  "programming",
    "limit"    :  '5'
}

headers = {
    "X-Api-Key": _My api key_,
    'User-Agent': 'curl/7.74.0'
}

response= requests.get(url=url, headers=headers, params=querystring)
print(response.headers)

with open('programming_questions.json', 'w') as outfile:
    json.dump(response.json(), outfile, indent=4)
```
You will see there is no questions found in that file. @bobbyiliev 
I want to get any of the category it is mentioned in the quizapi website.
Is there anyway to fix this issue? Then kindly let me know.
Actually, I'm trying to build a discord bot that will let users evaluate their skills by answering these questions. There will be a point system for answering the correct options. Basically, I don't want to use any other APIs because your question quality is very good and so knowledgable. Isn't that a cool thing?  😃😎
I hope this issue will be solved too, I'm eagerly waiting for that. Thanks!

![Screenshot (127)](https://user-images.githubusercontent.com/42302494/129615723-7158f3cb-96c5-4988-99a0-08f49a62a0b9.png)

**Comment by bobbyiliev** [comment]
Hi there,

I could suggest using the `tags` rather than the `category`. Let me know how it goes!

**Comment by SouvikGhosh05** [comment]
Hi there, 
I just tried using `tags`, but sorry it didn't work at all.

**Comment by bobbyiliev** [comment]
Just tried with tags and it worked:

![image](https://user-images.githubusercontent.com/21223421/130102456-233358a4-372f-4d30-9d9f-5fd5fa8a6b4d.png)

**Comment by SouvikGhosh05** [comment]
It is not showing results for `Networking`, `Programming` and `Cloud` topics.

**Comment by bobbyiliev** [comment]
Actually, you can find the available categories directly here:

https://quizapi.io/categories

The categories that you are trying to use do not really exist which would explain why you are seeing 0 questions returned.
